micronaut:
  application:
    name: cardsbackend
  router:
    static-resources:
      jsonschema:
        paths: classpath:META-INF/schemas
        mapping: /schemas/**
      swagger:
        paths: classpath:META-INF/swagger
        mapping: /swagger/**
      swagger-ui:
        paths: classpath:META-INF/swagger/views/swagger-ui
        mapping: /swagger-ui/**
  security:
    intercept-url-map:
    - pattern: /swagger/**
      access: isAnonymous()
    - pattern: /swagger-ui/**
      access: isAnonymous()
    authentication: bearer
    token:
      jwt:
        signatures:
          secret:
            generator:
              secret: ${JWT_GENERATOR_SIGNATURE_SECRET:shh1w0rk4tTh3B4nkH3r3s4d0ll4r}
  server:
    port: 8081
datasources:
  default:
    url: jdbc:postgresql://oli-dev.hu:5432/study
    driver-class-name: org.postgresql.Driver
    db-type: postgres
    username: card_backend
    password: titok
    schema: cards
    schema-generate: CREATE_DROP
jpa:
  default:
    entity-scan:
      packages: 'hu.devoli'
    properties:
      hibernate:
        hbm2ddl:
          auto: update
        show_sql: true
